type: custom:apexcharts-card
now:
  show: true
  label: now
graph_span: 8d
experimental:
  color_threshold: true
apex_config:
  grid:
    show: true
    borderColor: dimgray
    strokeDashArray: 4
  chart:
    height: 384px
  legend:
    showForSingleSeries: false
    show: false
  plotOptions:
    bar:
      borderRadius: 3
  yaxis:
    min: 0
    decimalsInFloat: 0
    forceNiceScale: true
  xaxis:
    type: datetime
    labels:
      datetimeFormatter:
        minute: HH:mm
        day: ddd
all_series_config:
  curve: stepline
  show:
    offset_in_name: true
header:
  title: Tuulivoimaennuste MW
  show: true
  show_states: true
  colorize_states: true
span:
  start: day
series:
  - entity: sensor.nordpool_kwh_fi_eur_3_10_0
    type: line
    float_precision: 0
    stroke_width: 2
    opacity: 1
    unit: MW
    name: Tuulivoima
    color_threshold:
      - value: 2000
        color: forestgreen
        opacity: 1
      - value: 1000
        color: gold
        opacity: 1
      - value: 900
        color: darkred
        opacity: 1
    show:
      in_header: false
      legend_value: false
      extremas: false
    data_generator: |
      const processData = async () => {
        const response = await fetch('https://raw.githubusercontent.com/vividfog/nordpool-predict-fi/main/deploy/windpower.json');
        const predictionData = await response.json();
        return predictionData.map(([timestamp, value]) => [parseInt(timestamp), value]);
      };
      return processData();
